apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postink
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jarovo/postink.git
    path: helm
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: postink
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
