apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: minikube-eu
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
        - git:
            repoURL: https://github.com/jarovo/apps.git
            revision: HEAD
            directories:
            - path: eu-apps/*
        - clusters:    
            selector:
              matchLabels:
                type: "workload"     
                region: "eu"                     
  template:      
    metadata:
      name: 'eu-only-{{index .path.segments 1}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/jarovo/apps.git
        targetRevision: HEAD
        path: '{{.path.path}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: 'eu-only-{{index .path.segments 1}}'

      syncPolicy:
        syncOptions:
          - CreateNamespace=true  
        automated: 
          prune: true
          selfHeal: true 
